version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: banking-db
    environment:
      POSTGRES_DB: banking_system
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: