ALTER TABLE budgets
    ADD COLUMN period VARCHAR NOT NULL DEFAULT 'MONTHLY',
    ADD COLUMN status VARCHAR NOT NULL DEFAULT 'ACTIVE';

COMMENT ON COLUMN budgets.period IS 'WEEKLY, MONTHLY, YEARLY';
COMMENT ON COLUMN budgets.status IS 'ACTIVE, EXPIRED';