# Application
app.name=Enterprise Banking System
app.version=1.0-SNAPSHOT

# Database - Neon (used by HikariCP / DatabaseConnection.java)
db.url=jdbc:postgresql://ep-dark-smoke-azma18g2-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
db.username=neondb_owner
db.password=npg_KdYOlR0HrnQ6
db.driver=org.postgresql.Driver

# HikariCP (Phase 3)
db.pool.size=10
db.pool.maxLifetime=30

# Flyway (used by flyway-maven-plugin in pom.xml)
flyway.url=jdbc:postgresql://ep-dark-smoke-azma18g2-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
flyway.user=neondb_owner
flyway.password=npg_KdYOlR0HrnQ6